### PR TITLE
Add hive-shims dependency.

### PR DESCRIPTION
**Pull request by arhimondr**
It is required for supporting kerberos protected hive servers

### CODE REVIEW

**Comment by electrum** [comment]
I'll get this merged and released.

The commit message title is too long, please limit to ~50 characters. See this great guide: http://chris.beams.io/posts/git-commit/

**Comment by arhimondr** [comment]
Great article. Thanks for pointing me out on this.

**Comment by electrum** [comment]
Merged, thanks!

**Comment by electrum** [comment]
Released 0.13.1-3

**Pull request merged**
