### PR TITLE
Build fat jar for Hive JDBC 0.13.1

### PR DESCRIPTION
**Pull request by losipiuk**
@electrum 
This is initial build for fat hive jdbc jar. It is based on on Hive 0.13.1.
I decided on keeping versioning scheme which consists of hive version suffixed with release number.

Please take a look

### CODE REVIEW

**Comment by kokosing** [comment]
@electrum Can we push that?

**Comment by electrum** [comment]
Merged, thanks!

**Comment by electrum** [comment]
I just released `0.13.1-1` to Maven Central

**Comment by losipiuk** [comment]
Thanks!

**Pull request merged**
