### PR TITLE
Shade hive common classes

### PR DESCRIPTION
**Pull request by kokosing**
Shade hive common classes

This is yet another conflict with presto-hive-apache, both
presto-hive-jdbc and presto-hive-apache were containing this classes

### CODE REVIEW

**Comment by kokosing** [comment]
This should be the last. I spotted the previous one when I was working on tempto, this one when I was trying to use new tempto with Presto. I should had test that with Presto before so we could do single release, sorry.

@electrum Can you please take a look? And if it is ok to you, can you please merge and do a release?

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
@kokosing  Why not shade everything which is not strictly interface of JDBC driver?

**Comment by kokosing** [comment]
@losipiuk I updated this PR. Now all besided jdbc classes are shaded.

**Comment by losipiuk** [comment]
Thanks. Looks good.

**Comment by kokosing** [comment]
@electrum can you please do a release?

**Comment by electrum** [comment]
@kokosing released `0.13.1-5`

**Comment by kokosing** [comment]
@electrum Thank you!

**Pull request merged**
